root: true
extends:
  - standard
  - standard-react
  - plugin:jsx-a11y/strict
plugins:
  - jsx-a11y
  - react-hooks
env:
  browser: true
overrides:
  - files:
      - "__mocks__/**/*.{js,jsx}"
      - "*.test.{js,jsx}"
    env:
      jest: true
    rules:
      "react/prop-types": false
rules:
  "jsx-a11y/label-has-for": off
  "react-hooks/rules-of-hooks": "error"
  "react-hooks/exhaustive-deps": "warn"
